# Generated by Django 4.0.4 on 2022-04-24 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_rename_content_post_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.CharField(default=1, max_length=3000),
            preserve_default=False,
        ),
    ]
