# Generated by Django 4.0.4 on 2022-11-05 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_alter_post_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='stock_det',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('cate', models.CharField(max_length=200, null=True)),
                ('qua', models.CharField(max_length=200, null=True)),
                ('num', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
