# Generated by Django 4.0.4 on 2022-11-05 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_stock_det'),
    ]

    operations = [
        migrations.CreateModel(
            name='revw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=200, null=True)),
                ('uname', models.CharField(max_length=200, null=True)),
                ('review', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
