# Generated by Django 4.0.4 on 2022-11-05 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_revw'),
    ]

    operations = [
        migrations.AddField(
            model_name='revw',
            name='rate',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
