# Generated by Django 4.0.1 on 2022-11-12 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_stock_det_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='revw',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.shop'),
        ),
    ]
