# Generated by Django 4.0.1 on 2022-11-12 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_revw_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revw',
            name='shop',
        ),
    ]
