# Generated by Django 4.0.1 on 2022-11-12 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_remove_revw_shop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='shop_name',
            new_name='kudumbasree_unit',
        ),
    ]
